apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
  labels:
    type: Deployment
    author: Mamoon-Ashraf
  annotations:
    session: 6th-batch
spec:
  replicas: 3
  stratagey:
    type: "RollingUpdate"
    rollingupdate:
      maxunavailable: 0
      maxsurge: 1
  selector:
    matchLabels:
       app: node-app
    
      
  template:
    metadata:
      labels:
       app: node-app
       author: Mamoon-Ashraf
        
    spec:
      containers:
      - name: node-frontend
        image: mamoon123/frontend-app/:v1.1
        ports:
        - containerPort: 8080
          name: tcp

---
apiVersion: v1
kind: Service
metadata:
  name: node-app
spec:
  type: NodePort
  selector:
    app: node-app
  
  ports:
  - protocol: TCP
  # service port to recieve traffic
    port: 8080
    # container port to recieve the traffic
    targetPort: 8080
    # nodeip:port to recieve the external traffic into cluster
    nodePort: 33000